apiVersion: v1
kind: ConfigMap
metadata:
  name: heimdall-config
  namespace: default
data:
  kafka-bootstrap-servers: "kafka:9092"
  elasticsearch-uris: "http://elasticsearch:9200"
  redis-host: "redis"
  redis-port: "6379"
  log-retention-days: "90"
  analysis-enabled: "true"
  notification-enabled: "true"
