apiVersion: v1
kind: Secret
metadata:
  name: heimdall-secrets
  namespace: default
type: Opaque
stringData:
  database-url: "jdbc:postgresql://postgres:5432/heimdall"
  database-username: "heimdall"
  database-password: "CHANGE_ME_IN_PRODUCTION"
  elasticsearch-username: ""
  elasticsearch-password: ""
  redis-password: ""
